- hosts: control
  tasks:
    - debug:
      
- hosts: satellite
  tasks:
    - debug:

- name: Add subscription
  hosts: load_balancers,database_servers,backend_servers
  gather_facts: true
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod
  tasks:
    - debug:
        msg: "{{ hostvars['control'].ansible_default_ipv4.address }}, {{ hostvars['control'].ansible_dns.nameservers.0 }} "
    - name: Insert DNS IP
      command: >-
        nmcli connection modify "System eth0"
        ipv4.ignore-auto-dns yes
        ipv4.dns {{ hostvars['control'].ansible_default_ipv4.address }}
        +ipv4.dns {{ hostvars['control'].ansible_dns.nameservers.1 }}
        +ipv4.dns 8.8.8.8

    - name: add satellite to /etc/hosts
      lineinfile:
        state: present
        path: /etc/hosts
        line: "{{ hostvars['satellite'].ansible_default_ipv4.address }} {{ hostvars.satellite.ansible_fqdn }}"

    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted

    - name: install katello-ca-consumer package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: true
        state: present

    - name: register system and attach subs
      redhat_subscription:
        state: present
        activationkey: "{{ satellite_activationkey }}"
        org_id: "{{ satellite_org }}"
        auto_attach: true

    - name: install firewalld
      yum:
        name: firewalld
        state: latest

    - name: start firewalld
      service: 
        name: firewalld
        state: started
        enabled: yes
