---

- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: false
  collections:
    - community.postgresql
  tags:
    - database_servers

  pre_tasks:
    - debug:
        msg: "Start postgress server setup"

    - name: Install Firewalld
      yum:
        name: firewalld
        state: latest
   
    - name: Start firewalld
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: Open service port
      firewalld:
        service: postgresql
        state: enabled
        immediate: true
        permanent: true

    - name: Open tcp port
      firewalld:
        port: 5432/tcp
        permanent: yes
        immediate: yes
        state: enabled

  roles:
  
    - postgres

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: true
  tags:
    - application_servers

  pre_tasks:
    - debug:
        msg: "Start postgress server setup"

    - name: Install Firewalld
      yum:
        name: firewalld
        state: latest

    - name: Start firewalld
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: Open service port
      firewalld:
        service: postgresql
        state: enabled
        immediate: true
        permanent: true

    - name: Open tcp port
      firewalld:
        port: 5432/tcp
        permanent: yes
        immediate: yes
        state: enabled
        
  roles:
    - final_flask
    #- flask
    
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true

  tags:
    - load_balancers

  roles:

    - haproxy

...    
