---

- name: Play to setup postgres server
  hosts: database_servers
  tasks:
    - debug:
        msg: "Start postgress server setup"

    - name: Setup firewall
      include_role:
        name: final_firewall
      vars:
        firewall_services:
          - postgress
        firewall_ports:
          - 5432

    - name: Setup mysql server
      include_role:
        name: final_postgres10

    - debug:
        msg: "Finished postgres server setup"

