---
# defaults file for final_postgres10

postgres_rhel8_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
postgres_packages:
  - postgresql
  - postgresql-server
  - postgresql-contrib
  - postgresql-libs
postgres_library: python39-psycopg2
postgres_10_data_dir: /var/lib/pgsql/10/data
postgres_10_bin_path: /usr/pgsql-10/bin
postgres_service: postgresql-10.service
postgres_port: 5432
postgres_user: postgres
postgres_users:
  - name: flask
    password: redhat
    database: flask_db
    state: present
    priv: ALL
postgres_databases:
  - name: flask_db
    owner: flask
  - name: books_store
    owner: flask
